# Rede Neural NEAT

Esta é uma implementação da rede neural NEAT (NeuroEvolution of Augmenting Topologies) em C++.

## Estrutura
- /include: Arquivos de cabeçalho
- /src: Arquivos fonte
- /docs: Documentação

## Como usar
1. Copie a pasta RedeNeural para seu projeto
2. Inclua os headers necessários
3. Configure o Makefile para incluir os arquivos da rede neural

## Exemplo de uso
\\\cpp
#include "RedeNeural/include/Populacao.h"

// Criar uma população
NEAT::Populacao populacao(numEntradas, numSaidas);

// Evoluir a população
populacao.evoluir();
\\\
"@ | Out-File -FilePath "RedeNeural/README.md" -Encoding UTF8

# Criar um Makefile de exemplo
@"
# Diretórios
REDE_NEURAL_DIR = RedeNeural
INCLUDE_DIR = \/include
SRC_DIR = \/src

# Arquivos fonte Rede Neural
REDE_NEURAL_SOURCES = \
OBJECTS = \

# Compilador e flags
CXX = g++
CXXFLAGS = -I\ -std=c++17

# Regras
all: \

%.o: %.cpp
\ \ -c \$< -o \$@

clean:
rm -f \
